# CloudFormationTemplateVersion
# Description

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation Template for RDS'
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'MyNewRDS'
      MasterUsername: 'admin'
      MasterUserPassword: '<not_set_temp_keys>'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'mysql'
      EngineVersion: '8.0.35'
      AllocatedStorage: 20
      BackupRetentionPeriod: 7